# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0003_auto_20160803_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='dob',
            field=models.TextField(blank=True, null=True),
        ),
    ]
