# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0005_auto_20160803_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.Category'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.CharField(max_length=80),
        ),
    ]
